All pages
zFarrukh/budgetify pull request #9
Opened 2022-04-15 08:20 UTC by zFarrukh

2022-04-15 15:03 UTC, vokanred commented
Update the branch and resolve conflicts

2022-04-15 17:28 UTC, zFarrukh commented
resolved

2022-04-18 05:29 UTC, vokanred commented
https://user-images.githubusercontent.com/93642893/163759484-cd234e91-a2e5-454f-acec-36bf6334b3a3.mov

When I create the second account the form is initially red

2022-04-18 05:30 UTC, vokanred commented
![Screen Shot 2022-04-18 at 8 30 10 AM](https://user-images.githubusercontent.com/93642893/163759587-a80c1ce4-7e74-4e89-87f7-d72c2644fc60.png)

NaN values in a table

2022-04-18 05:33 UTC, vokanred commented
https://user-images.githubusercontent.com/93642893/163759786-f497534f-502b-456b-a945-4a1be14efa86.mov

Account details button is not shown sometimes

2022-04-18 05:35 UTC, vokanred commented
Comments above just my observations that are not related to current PR. You can fix them when you want, but I think it's very important for demo.

Now starting to review the code

2022-04-18 05:56 UTC, vokanred requested changes
I haven't completed the review.

Fix all drawers. Use Drawer API instead of custom CSS.
Also you should unsubscribe everywhere but it is not so important for now.

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/categories-page.component.ts
> +        this.categoryService.getCategories().subscribe({
Duplication

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/categories-page.component.ts
> +    this.categoryService.getCategories().subscribe({
Duplication

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/categories-page.component.ts
> +    this.categoryService.getCategories().subscribe({
Create a method for getting categories

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/categories-page.component.ts
>  export class CategoriesPageComponent implements OnInit {
You should unsubscribe from every subscription

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/categories-page.component.ts
>  export class CategoriesPageComponent implements OnInit {
You can use https://github.com/ngneat/until-destroy to make it easier

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/category-add/category-add.component.html
> +  [ngClass]="open ? '' : 'display-none'"
[class.display-none]="!open"

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/category-add/category-add.component.html
> +  [ngClass]="open ? '' : 'display-none'"
But anyway you shouldn't hide the drawer this way. The drawer has API for closing

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/category-add/category-add.component.ts
> +  @ViewChild('drawer') drawer: any;
You don't need to call close() manually

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/category-add/category-add.component.ts
> +  @ViewChild('drawer') drawer: any;
Use [opened] input

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/category-add/category-add.component.ts
> +        setTimeout(() => {
Don't call open() manually.

If you want to add setTimeout it's a good indicator that you're doing you are doing something wrong. :)

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/category-item/category-item.component.html
> +      [value]="category.title"
You shouldn't use [value] if you use formControl

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/category-item/category-item.component.html
> +      [ngClass]="isEditMode ? 'edit' : ''"
[class.edit]="isEditMode"

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/categories-page/category-item/category-item.component.ts
> +    dialogRef.afterClosed().subscribe((id) => {
unsubscribe

2022-04-18 05:56 UTC, vokanred commented on client/src/app/categories/category.service.ts
> +  public categories: ICategory[] = [];
You store categories here and also in categories page component

2022-04-18 05:56 UTC, vokanred commented on client/src/app/main/main-page/account/account-detail/account-detail.component.html
> +  [ngClass]="account ? '' : 'display-none'"
the same

2022-04-18 05:56 UTC, vokanred commented on client/src/app/main/main-page/account/account-detail/account-detail.component.ts
> +    this.drawer.close();
same

2022-04-18 05:56 UTC, vokanred commented on client/src/app/main/main-page/account/account-detail/account-detail.component.ts
> +export class AccountDetailComponent implements OnInit {
Remove drawer ref

2022-04-18 05:56 UTC, vokanred commented on client/src/app/main/main-page/account/account-edit/account-edit.component.ts
> +  @ViewChild('drawer') drawer: any;
Remove drawer ref

2022-04-19 05:34 UTC, vokanred commented
I see that you've implemented background for drawer. That is great but rawer container already has implementation for that. 

@Input()
hasBackdrop: boolean

2022-04-19 05:35 UTC, vokanred commented
Every material component has a page with examples where you can find your case.

https://material.angular.io/components/sidenav/examples

2022-04-21 11:15 UTC, vokanred approved these changes
Approved

2022-04-21 11:33 UTC, merged